apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: qa-oms
  annotations:
    kompose.cmd: D:\Instaladores\kompose\kompose.exe 
    --file docker-compose.yml convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: dev-agendamiento-cedi
  name: dev-agendamiento-cedi
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dev-agendamiento-cedi
    spec:
      containers:
      - image: qaacrintegracion.azurecr.io/dev-agendamiento-cedi:1.0
        name: dev-agendamiento-cedi
        resources: {}
      restartPolicy: Always
status: {}
